### ISSUE TITLE
Is there a way to access the links within the template?

### ISSUE THREAD

**Issue by GeorgeD121** [hut6/SimpleSharing#2]

**Comment by reganlawton** [comment]
@GeorgeD121 So your asking for a way to generate social sharing links via twig for the rendered page?

    {{ facebook_link }}

Something like that?

**Comment by GeorgeD121** [comment]
Yes exactly

**Comment by reganlawton** [comment]
I guess I can look into adding this feature, it wasn't the main aim for this plugin, but a twig extension is easy enough to add for facebook, twitter and google and possible email, with supporting link options.

**Comment by reganlawton** [comment]
Added in 1.1.0 release
