### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by strohrdanz** [hut6/SimpleSharing#3]
I'm getting this error: 

`The requested URL /_simple_sharing_url was not found on this server.`

![screen shot 2016-03-08 at 10 54 58 am](https://cloud.githubusercontent.com/assets/7017098/13606976/3d06ca54-e51c-11e5-9b27-89323c92eb3a.png)

Any ideas?

**Comment by reganlawton** [comment]
Would you be able to provide more information on your configuration? As the build is working with latest releases.
