### ISSUE TITLE
Not found links from the right sidebar

### ISSUE THREAD

**Issue by dvago** [hut6/SimpleSharing#4]
Hi there,

Following your installation instructions this is what I get once the plugin is installed from the settins panel.

Would you mind check please?

![screen shot 2017-04-05 at 13 59 47](https://cloud.githubusercontent.com/assets/5074033/24706635/444cdd68-1a08-11e7-884f-ecfa401e902a.png)

The generated links are pointing to this:
https://www.facebook.com/sharer/sharer.php?u=%3C!DOCTYPE%20HTML%20PUBLIC

**Comment by reganlawton** [comment]
@dvago Can you confirm with is still happening? I believe this was resolved in #3 and our v1.1.4 release and was due to a route error in the newer CraftCMS versions under certain build configs
